services:
  postgres:
    image: postgres:16
    container_name: tmdt_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: tmdt_redis
    restart: unless-stopped
    command: >
      sh -c '
        if [ -n "$$REDIS_PASSWORD" ]; then
          exec redis-server --requirepass "$$REDIS_PASSWORD";
        else
          exec redis-server;
        fi
      '

    ports:
      - "6379:6379"
    volumes:
      - ./docker-data/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:4
    container_name: tmdt_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

networks:
  default:
    name: tmdt_net
